#pragma once

#define MINISPEEDCONTROLLER_USART_PIN_TX    GPIO_Pin_5
#define MINISPEEDCONTROLLER_USART_PIN_RX    GPIO_Pin_6
#define MINISPEEDCONTROLLER_USART_PORT      GPIOD
#define MINISPEEDCONTROLLER_USART_PORT_RCC  RCC_PB2Periph_GPIOD
#define MINISPEEDCONTROLLER_USART_RCC       RCC_PB2Periph_USART1

void minispeedcontroller_usart_init(void);